<?php
namespace hschulz\JenkinsPHPReference;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-19 at 17:52:04.
 */
class ExampleClassTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ExampleClass
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ExampleClass;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers hschulz\JenkinsPHPReference\ExampleClass::add
     * @todo   Implement testAdd().
     */
    public function testAdd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hschulz\JenkinsPHPReference\ExampleClass::divide
     * @todo   Implement testDivide().
     */
    public function testDivide()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hschulz\JenkinsPHPReference\ExampleClass::multiply
     * @todo   Implement testMultiply().
     */
    public function testMultiply()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hschulz\JenkinsPHPReference\ExampleClass::substract
     * @todo   Implement testSubstract().
     */
    public function testSubstract()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
